# Generated by Django 5.0.6 on 2024-08-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiveSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='divespot_name')),
                ('description', models.TextField(blank=True, verbose_name='divespot_description')),
                ('accurate_location', models.BooleanField()),
                ('dive_type', models.CharField(choices=[('Reef', 'Reef'), ('Wall', 'Wall'), ('Wreck', 'Wreck'), ('Cave', 'Cave'), ('Cavern', 'Cavern'), ('Open Water', 'Open Water')], default='Open Water', max_length=30)),
                ('access_type', models.CharField(choices=[('On Foot', 'On Foot'), ('By Boat', 'By Boat'), ('Unknown', 'Unknown')], default='Unknown', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='divespot',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='marker_divespot', to='markers.divespot'),
        ),
    ]
