# Generated by Django 5.0.6 on 2024-08-05 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_divespot_marker_divespot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='divespot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marker_divespot', to='markers.divespot'),
        ),
    ]
